steps:
  - label: ":playwright: Run Playwright Tests"
    command:
      - npm install
      - mkdir -p logs
      - npm test | tee logs/playwright-test.log
    agents:
      queue: "default"
    artifact_paths:
      - "logs/*.log"
      - "playwright-report/**"
      - "test-results/**"
      - "**/*.png"
      - "**/*.mp4"
      - "trace.zip"
env:
      USERNAME: "$USERNAME"
      PASSWORD: "$PASSWORD"