steps:
  - label: ":playwright: Run Playwright Tests"
    command:
      - export $(grep -v '^#' .env | xargs)
      - npm install
      - mkdir -p logs
      - npm test | tee logs/playwright-test.log
    agents:
      queue: "default"
    artifact_paths:
      - "logs/*.log"
      - "playwright-report/**"
      - "test-results/**"
      - "**/*.png"
      - "**/*.mp4"
      - "trace.zip"