steps:
  - label: ":playwright: Run Playwright Tests"
    command:
      - npm install
      - mkdir -p logs
      - 'echo "USERNAME: $USERNAME"'
      - 'if [ -z "$PASSWORD" ]; then echo "PASSWORD: NOT SET"; else echo "PASSWORD: ********"; fi'
      - USERNAME=$USERNAME PASSWORD=$PASSWORD npm test | tee logs/playwright-test.log
    agents:
      queue: "default"
    artifact_paths:
      - "logs/*.log"
      - "playwright-report/**"
      - "test-results/**"
      - "**/*.png"
      - "**/*.mp4"
      - "trace.zip"
    env:
      USERNAME: "$USERNAME"
      PASSWORD: "$PASSWORD"
