steps:
  - label: ":playwright: Run Playwright Tests"
    command:
      - 'export USERNAME=$(buildkite-agent secret get USERNAME) && export PASSWORD=$(buildkite-agent secret get PASSWORD)'
      - 'npm install'
      - 'mkdir -p logs'
      - 'npm test | tee logs/playwright-test.log || exit 1'
    agents:
      queue: "default"
    artifact_paths:
      - "logs/*.log"
      - "playwright-report/**"
      - "test-results/**"
      - "**/*.png"
      - "**/*.mp4"
      - "trace.zip"
